from card import Card
import random

class Deck:
    def __init__(self):
        self.deck = []
        self.initialise_deck()
        random.shuffle(self.deck)

    def get_card(self):
        return self.deck.pop()
    
    def initialise_deck(self):
        self.deck.append(Card('January', 'Plain', 'assets/cards/january_plain.jpg', 1))
        self.deck.append(Card('January', 'Plain', 'assets/cards/january_plain2.jpg', 1))
        self.deck.append(Card('January', 'Poetry Ribbon', 'assets/cards/january_poetryribbon.jpg', 5))
        self.deck.append(Card('January', 'Bright', 'assets/cards/january_bright.jpg', 20))
        self.deck.append(Card('February', 'Plain', 'assets/cards/february_plain.jpg', 1))
        self.deck.append(Card('February', 'Plain', 'assets/cards/february_plain2.jpg', 1))
        self.deck.append(Card('February', 'Poetry Ribbon', 'assets/cards/february_poetryribbon.jpg', 5))
        self.deck.append(Card('February', 'Animal', 'assets/cards/february_animal.jpg', 10))
        self.deck.append(Card('March', 'Plain', 'assets/cards/march_plain.jpg', 1))
        self.deck.append(Card('March', 'Plain', 'assets/cards/march_plain2.jpg', 1))
        self.deck.append(Card('March', 'Poetry Ribbon', 'assets/cards/march_poetryribbon.jpg', 5))
        self.deck.append(Card('March', 'Bright', 'assets/cards/march_bright.jpg', 20))
        self.deck.append(Card('April', 'Plain', 'assets/cards/april_plain.jpg', 1))
        self.deck.append(Card('April', 'Plain', 'assets/cards/april_plain2.jpg', 1))
        self.deck.append(Card('April', 'Red Ribbon', 'assets/cards/april_redribbon.jpg', 5))
        self.deck.append(Card('April', 'Animal', 'assets/cards/april_animal.jpg', 10))
        self.deck.append(Card('May', 'Plain', 'assets/cards/may_plain.jpg', 1))
        self.deck.append(Card('May', 'Plain', 'assets/cards/may_plain2.jpg', 1))
        self.deck.append(Card('May', 'Red Ribbon', 'assets/cards/may_redribbon.jpg', 5))
        self.deck.append(Card('May', 'Animal', 'assets/cards/may_animal.jpg', 10))
        self.deck.append(Card('June', 'Plain', 'assets/cards/june_plain.jpg', 1))
        self.deck.append(Card('June', 'Plain', 'assets/cards/june_plain2.jpg', 1))
        self.deck.append(Card('June', 'Blue Ribbon', 'assets/cards/june_blueribbon.jpg', 5))
        self.deck.append(Card('June', 'Butterfly', 'assets/cards/june_butterfly.jpg', 10))
        self.deck.append(Card('July', 'Plain', 'assets/cards/july_plain.jpg', 1))
        self.deck.append(Card('July', 'Plain', 'assets/cards/july_plain2.jpg', 1))
        self.deck.append(Card('July', 'Red Ribbon', 'assets/cards/july_redribbon.jpg', 5))
        self.deck.append(Card('July', 'Boar', 'assets/cards/july_boar.jpg', 10))
        self.deck.append(Card('August', 'Plain', 'assets/cards/august_plain.jpg', 1))
        self.deck.append(Card('August', 'Plain', 'assets/cards/august_plain2.jpg', 1))
        self.deck.append(Card('August', 'Animal', 'assets/cards/august_animal.jpg', 10))
        self.deck.append(Card('August', 'Bright', 'assets/cards/august_bright.jpg', 20))
        self.deck.append(Card('September', 'Plain', 'assets/cards/september_plain.jpg', 1))
        self.deck.append(Card('September', 'Plain', 'assets/cards/september_plain2.jpg', 1))
        self.deck.append(Card('September', 'Blue Ribbon', 'assets/cards/september_blueribbon.jpg', 5))
        self.deck.append(Card('September', 'Animal', 'assets/cards/september_bright.jpg', 10))
        self.deck.append(Card('October', 'Plain', 'assets/cards/october_plain.jpg', 1))
        self.deck.append(Card('October', 'Plain', 'assets/cards/october_plain2.jpg', 1))
        self.deck.append(Card('October', 'Blue Ribbon', 'assets/cards/october_blueribbon.jpg', 5))
        self.deck.append(Card('October', 'Deer', 'assets/cards/october_deer.jpg', 10))
        self.deck.append(Card('November', 'Plain', 'assets/cards/november_plain.jpg', 1))
        self.deck.append(Card('November', 'Red Ribbon', 'assets/cards/november_redribbon.jpg', 1))
        self.deck.append(Card('November', 'Animal', 'assets/cards/november_animal.jpg', 10))
        self.deck.append(Card('November', 'Rain Man', 'assets/cards/november_rainman.jpg', 20))
        self.deck.append(Card('December', 'Plain', 'assets/cards/december_plain.jpg', 1))
        self.deck.append(Card('December', 'Plain', 'assets/cards/december_plain2.jpg', 1))
        self.deck.append(Card('December', 'Plain', 'assets/cards/december_plain3.jpg', 1))
        self.deck.append(Card('December', 'Bright', 'assets/cards/december_bright.jpg', 20))
